[package]
name = "auto-rust"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myself = "0.5.0"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
