[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "3.0.1"
tokio = { version = "1.38.0", features = ["full"] }
auto-rust.workspace = true
